name: web_fonts_example
description: web fonts package example
publish_to: none

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  web_fonts:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: NotoSansCJKKRLocal
      fonts:
        - asset: fonts/NotoSansCJKkr-Black.otf
          weight: 900
        - asset: fonts/NotoSansCJKkr-Bold.otf
          weight: 700
        - asset: fonts/NotoSansCJKkr-Medium.otf
          weight: 500
        - asset: fonts/NotoSansCJKkr-Regular.otf
          weight: 300
        - asset: fonts/NotoSansCJKkr-Thin.otf
          weight: 100